const Discord = require('discord.js');
const Twit = require('twit');
const { Client, GatewayIntentBits } = require('discord.js');

// Twitter API credentials
const consumerKey = 'Your key here';
const consumerSecret = 'Your secret here';
const accessToken = 'Your token here';
const accessTokenSecret = 'Your token secret here';

// Array of influential account usernames
const influentialAccounts = [
  '@BarackObama',
  '@realDonaldTrump',
  '@narendramodi',
  '@JustinTrudeau',
  '@EmmanuelMacron',
  '@BorisJohnson',
  '@jacindaardern',
  '@KamalaHarris',
  '@JoeBiden',
  '@jairbolsonaro',
  '@lopezobrador_',
  '@xi_jinping',
  '@AbeShinzo',
  '@KremlinRussia_E',
  '@ScottMorrisonMP',
  '@RTErdogan',
  '@vonderleyen',
  '@markrutte',
  '@matteosalvinimi',
  '@CyrilRamaphosa',
  '@moonriver365',
  '@alferdez',
  '@antonioguterres',
  '@sheikhhasina',
  '@wthmanas',
  '@CNN',
'@BBCNews',
'@nytimes',
'@Reuters',
'@washingtonpost',
'@NBCNews',
'@ABC',
'@FoxNews',
'@AP',
'@CBSNews',
'@guardian',
'@AJEnglish',
'@business',
'@HuffPost',
'@TIME',
'@USATODAY',
'@WSJ',
'@FT',
'@latimes',
'@Independent',
'@Telegraph',
'@Forbes',
'@TheEconomist',
'@politico',
'@mashable',
'@NPR',
'@thedailybeast',
'@HuffPost',
'@BostonGlobe',
'@smh',
'@timesofindia',
'@australian',
'@cnni',
'@SkyNews',
'@thetimes',
'@DailyMirror',
'@TheSun',
'@TelegraphNews',
'@FinancialTimes',
'@NewYorker',
'@NatGeo',
'@espn',
'@SInow',
'@Variety',
'@RollingStone',
'@billboard',
'@voguemagazine',
'@people',
'@EW',
'@TMZ',
'@enews',
'@THR',
'@MTVNEWS',
'@IGN',
'@TechCrunch',
'@engadget',
'@mashabletech',
'@CNET',
'@WIRED',
'@verge',
'@Gizmodo',
'@ZDNet',
'@PCMag',
'@TheNextWeb',
'@VentureBeat',
'@axios',
'@MotherJones',
'@theintercept',
'@TheAtlantic',
'@voxdotcom',
'@BuzzFeed',
'@mashsocialmedia',
'@socialmedia2day',
'@techradar',
'@mashablescience',
'@NPR',
'@CNNPolitics',
'@BBCPolitics',
'@thehill',
'@POLITICOEurope',
'@bbcworldservice',
'@STcom',
'@usatodaysports',
'@ESPNcricinfo',
'@BBCSport',
'@NBCSports',
'@BleacherReport',
'@guardian_sport',
'@SkySports',
'@CNNBusiness',
'@washpostbiz',
'@FTBiz',
'@CNBC',
'@BW',
'@businessinsider',
'@mashbusiness',
'@ForbesTech',
'@verge',
'@mashabletechnews',
'@guardiantech',
'@BBCNews',
'@nytimes',
'@Reuters',
'@washingtonpost',
'@NBCNews',
'@ABC',
'@FoxNews',
'@AP',
'@CBSNews',
'@guardian',
'@AJEnglish',
'@business',
'@HuffPost',
'@TIME',
'@USATODAY',
'@WSJ',
'@FT',
'@latimes',
'@Independent',
'@Telegraph',
'@Forbes',
'@TheEconomist',
'@politico',
'@mashable',
'@NPR',
'@thedailybeast',
'@HuffPost',
'@BostonGlobe',
'@smh',
'@timesofindia',
'@australian',
'@cnni',
'@SkyNews',
'@thetimes',
'@DailyMirror',
'@TheSun',
'@TelegraphNews',
'@FinancialTimes',
'@NewYorker',
'@NatGeo',
'@espn',
'@SInow',
'@Variety',
'@RollingStone',
'@billboard',
'@voguemagazine',
'@people',
'@EW',
'@TMZ',
'@enews',
'@THR',
'@MTVNEWS',
'@IGN',
'@TechCrunch',
'@engadget',
'@mashabletech',
'@CNET',
'@WIRED',
'@verge',
'@Gizmodo',
'@ZDNet',
'@PCMag',
'@TheNextWeb',
'@VentureBeat',
'@axios',
'@MotherJones',
'@theintercept',
'@TheAtlantic',
'@voxdotcom',
'@BuzzFeed',
'@mashsocialmedia',
'@socialmedia2day',
'@techradar',
'@mashablescience',
'@NPR',
'@CNNPolitics',
'@BBCPolitics',
'@thehill',
'@POLITICOEurope',
'@bbcworldservice',
'@STcom',
'@usatodaysports',
'@ESPNcricinfo',
'@BBCSport',
'@NBCSports',
'@BleacherReport',
'@guardian_sport',
'@SkySports',
'@CNNBusiness',
'@washpostbiz',
'@FTBiz',
'@CNBC',
'@BW',
'@businessinsider',
'@mashbusiness',
'@ForbesTech',
'@verge',
'@mashabletechnews',
'@guardiantech',
'@AQR_Capital',
'@Bridgewater',
'@BlackRock',
'@ManGroup',
'@TwoSigma',
'@ElliottAdvisors',
'@ThirdPointLLC',
'@Point72',
'@Citadel',
'@RenaissanceCap',
'@PaulsonCo',
'@BaupostGroup',
'@OchZiff',
'@TudorInvest',
'@CaxtonAssoc',
'@Coatue',
'@Balyasny',
'@PershingSquare',
'@VikingGlobal',
'@HighbridgeCap',
'@GoldmanSachs',
'@JPMorgan',
'@MorganStanley',
'@Citi',
'@BankofAmerica',
'@WellsFargo',
'@UBS',
'@Barclays',
'@DeutscheBank',
'@CreditSuisse',
'@HSBC',
'@BNPParibas',
'@SocieteGenerale',
'@Nomura',
'@ING_news',
'@StandardBankZA',
'@NatWest_Help',
'@SantanderBankUS',
'@ScotiabankViews',
'@BankofChina',
'@TDameritrade',
'@Etrade',
'@CharlesSchwab',
'@Fidelity',
'@IBKR',
'@thinkorswim',
'@tradestation',
'@Ally',
'@RobinhoodApp',
'@tastytrade',
'@WebullGlobal',
'@StashInvest',
'@NerdWallet',
'@Stocktwits',
'@barchart',
'@Yodlee',
'@Coinbase',
'@gemini',
'@krakenfx',
'@Bitstamp',
'@Apple',
'@Microsoft',
'@Amazon',
'@Google',
'@Facebook',
'@Netflix',
'@Tesla',
'@Adobe',
'@Salesforce',
'@Oracle',
'@IBM',
'@Intel',
'@Cisco',
'@HP',
'@Dell',
'@VMware',
'@Nvidia',
'@Qualcomm',
'@AMD',
'@Sony',
'@Samsung',
'@LGUS',
'@Panasonic',
'@Xiaomi',
'@AlibabaGroup',
'@TencentGlobal',
'@Baidu_Inc',
'@Nokia',
'@Twitter',
'@Snapchat',
'@Uber',
'@Airbnb',
'@SpaceX',
'@SlackHQ',
'@Zoom',
'@Pinterest',
'@Etsy',
'@TikTok',
'@Twitch',
'@Spotify',
'@PayPal',
'@Square',
'@Stripe',
'@Coinbase',
'@RobinhoodApp',
'@Venmo',
'@TransferWise',
'@RevolutApp',
'@Monzo',
'@N26',
'@Chime',
'@WeChatApp',
'@WhatsApp',
'@telegram',
'@signalapp',
'@discord',
'@reddit',
'@tumblr',
'@tiktok_us',
'@instagram',
'@facebookapp',
'@snapchat',
'@twitter',
'@linkedin',
'@youtube',
'@netflix',
'@amazon',
'@twitch',
'@spotify',
'@pinterest',
'@tiktok_us',
'@WIPO',
'@UN',
'@WHO',
'@NASA',
'@FDArecalls',
'@EU_Commission',
'@OECD',
'@WorldBank',
'@IMFNews',
'@RedCross',
'@UNICEF',
'@FEMA',
'@CDCgov',
'@WhiteHouse',
'@nytimesworld',
'@BBCWorld',
'@ReutersWorld',
'@UN_News_Centre',
'@hrw',
'@amnesty',
'@Change',
'@Oxfam',
'@Greenpeace',
'@WWF',
'@UNEP',
'@UNESCO',
'@unfoundation',
'@UNHumanRights',
'@UNAIDS',
'@UN_Women',
'@UNDP',
'@UNFPA',
'@UNmigration',
'@UNOCHA',
'@UNHCRgov',
'@UNICEFUSA',
'@UNHCRUK',
'@UNHCRUSA',
'@UNHCRCanada',
'@UNHCR_Europe',
'@UNHCRgov',
'@UNHCRUK',
'@UNHCRUSA',
'@UNHCRCanada',
'@UNHCR_Europe',
'@UNHCRItalia',
'@UNHCRBelgie',
'@UNHCRUK',
'@UNHCRUSA',
'@UNHCRCanada',
'@UNHCR_Europe',
'@UNHCRItalia',
'@UNHCRBelgie',
'@UNHCRDeutschland',
'@UNHCRfrance',
'@UNHCRAT',
'@UNHCRsvizzera',
'@UNHCRItalia',
'@UNHCRBelgie',
'@UNHCRDeutschland',
'@UNHCRfrance',
'@UNHCRAT',
'@UNHCRsvizzera',
'@UNHCRItalia',
'@UNHCRBelgie',
'@UNHCRDeutschland',
'@UNHCRfrance',
'@UNHCRAT',
'@UNHCRsvizzera',
'@UNHCRItalia',
'@UNHCRBelgie',
'@UNHCRDeutschland',
'@UNHCRfrance',
'@UNHCRAT',
'@UNHCRsvizzera',
'@UNHCRItalia',
'@UNHCRBelgie',
'@UNHCRDeutschland',
'@UNHCRfrance',
'@UNHCRAT',
'@UNHCRsvizzera',
'@UNHCRItalia',
'@UNHCRBelgie',
'@UNHCRDeutschland',
'@UNHCRfrance',
'@UNHCRAT',
'@UNHCRsvizzera',
'@UNHCRItalia',
'@UNHCRBelgie',
'@UNHCRDeutschland',
'@UNHCRfrance',
'@UNHCRAT',
'@UNHCRsvizzera',
'@UNHCRItalia',
'@UNHCRBelgie',
'@Cristiano',
'@KingJames',
'@neymarjr',
'@serenawilliams',
'@rogerfederer',
'@LewisHamilton',
'@mPinoe',
'@KobeBryant',
'@TigerWoods',
'@lindseyvonn',
'@TheRock',
'@MoSalah',
'@KDTrey5',
'@mPinoe',
'@Simone_Biles',
'@naomiosaka',
'@TomBrady',
'@MikeTyson',
'@RafaelNadal',
'@usainbolt',
'@FloydMayweather',
'@DjokerNole',
'@virat.kohli',
'@CarliLloyd',
'@alexmorgan13',
'@CMcCaffrey5',
'@swimone',
'@DangeRussWilson',
'@ZionW32',
'@TheNotoriousMMA',
'@DrewBrees',
'@paulpogba',
'@JimmyButler',
'@TeamMessi',
'@luka7doncic',
'@CJMcCollum',
'@giannis_an34',
'@M10_Official',
'@kevinlove',
'@DwyaneWade',
'@lauriehernandez',
'@StefTsitsipas',
'@CarusoDwight',
'@rudygobert27',
'@d_degeaofficial',
'@AlexZverev',
'@StephenCurry30',
'@AaronRodgers12',
'@JHarden13',
'@sabrina_i20',
'@MagicJohnson',
'@jakepaul',
'@AmirKhan',
'@sergeibaka',
'@sergeibaka',
'@luka7doncic',
'@NeymarJr',
'@ChrisPaul',
'@Ronaldo',
'@TheTraeYoung',
'@tyson_fury',
'@KDTrey5',
'@ShaneWarne',
'@NateDiaz209',
'@KingJames',
'@MoSalah',
'@S10Bird',
'@PaulPogba',
'@MichaelPhelps',
'@TigerWoods',
'@AaronDonald97',
'@TomBrady',
'@Simone_Biles',
'@serenawilliams',
'@Cristiano',
'@naomiosaka',
'@MikeTyson',
'@RafaelNadal',
'@DjokerNole',
'@lindseyvonn',
'@rogerfederer',
'@usainbolt',
'@FloydMayweather',
'@Mo_Farah',
'@VirgilvDijk',
'@DwyaneWade',
'@michellewkwan',
'@kaj33',
'@UsainBolt',
'@andy_murray',
'@giannis_an34',
'@alexmorgan13',
'@ABdeVilliers17',
'@TheNotoriousMMA',
'@GaryLineker',
'@TeamMessi',
'@lauriehernandez',
'@juventusfcen',
'@imVkohli',
'@TomDaley1994',
'@iamdaniyar',
'@MariaSharapova',
'@DaleSteyn62',
'@KDTrey5',
'@RafaelNadal',
'@kaj33',
'@Tyson_Fury',
'@serenawilliams',
'@naomiosaka'
];

// Discord bot client
const client = new Client({ 
  intents: [GatewayIntentBits.Guilds, GatewayIntentBits.GuildMessages]
});

// Twitter Stream Listener
class TweetStreamListener {
  constructor(handleNewTweet) {
    this.handleNewTweet = handleNewTweet;
  }

  onStatus(status) {
    // Filter tweets by influential accounts
    if (influentialAccounts.includes(status.user.screen_name.toLowerCase())) {
      const tweetContent = `Tweet from ${status.user.screen_name}: ${status.text}`;
      this.handleNewTweet(tweetContent);
    }
  }
}

// Handle new tweet by sending it to the Discord server
function handleNewTweet(tweetContent) {
  // Send the tweet to all guilds and channels
  client.guilds.cache.forEach((guild) => {
    guild.channels.cache.forEach((channel) => {
      if (channel instanceof Discord.TextChannel) {
        channel.send(tweetContent);
      }
    });
  });
}

// Start monitoring the Twitter stream
function startTweetStreaming() {
  const tweetListener = new TweetStreamListener(handleNewTweet);

  const twitterApi = new Twit({
    consumer_key: consumerKey,
    consumer_secret: consumerSecret,
    access_token: accessToken,
    access_token_secret: accessTokenSecret,
    timeout_ms: 60 * 1000, // 60 seconds timeout
  });

  const followIdsPromises = influentialAccounts.map((screenName) =>
    getUserData(screenName, twitterApi).then((userData) => userData.id_str)
  );

  Promise.all(followIdsPromises)
    .then((followIds) => {
      const tweetStream = twitterApi.stream('statuses/filter', {
        follow: followIds.join(','),
      });

      tweetStream.on('tweet', (tweet) => {
        tweetListener.onStatus(tweet);
      });

      tweetStream.on('error', (error) => {
        console.error('Twitter stream error:', error);
      });
    })
    .catch((error) => {
      console.error('Error retrieving user IDs:', error);
    });
}

// Get user data for a given screen name
function getUserData(screenNames, twitterApi) {
  return new Promise((resolve, reject) => {
    twitterApi.get('users/lookup', { screen_name: screenNames }, (error, data) => {
      if (error) {
        reject(error);
      } else {
        resolve(data);
      }
    });
  });
}

// Start monitoring the Twitter stream
function startTweetStreaming() {
  const tweetListener = new TweetStreamListener(handleNewTweet);

  const twitterApi = new Twit({
    consumer_key: consumerKey,
    consumer_secret: consumerSecret,
    access_token: accessToken,
    access_token_secret: accessTokenSecret,
    timeout_ms: 60 * 1000, // 60 seconds timeout
  });

  getUserData(influentialAccounts.join(','), twitterApi)
    .then((userData) => {
      const followIds = userData.map((user) => user.id_str);
      const tweetStream = twitterApi.stream('statuses/filter', {
        follow: followIds.join(','),
      });

      tweetStream.on('tweet', (tweet) => {
        tweetListener.onStatus(tweet);
      });

      tweetStream.on('error', (error) => {
        console.error('Twitter stream error:', error);
      });
    })
    .catch((error) => {
      console.error('Error retrieving user data:', error);
    });
}

// Run the Discord bot and start the tweet stream
client.login('Your bot token here')
  .then(() => {
    startTweetStreaming;
  })
  .catch((error) => {
    console.error('Failed to login:', error);
  });
  